force-app/main/default/objects/Concrete_Implementation__c/Concrete_Implementation__c.object-meta.xml
<CustomObject>
    <label>Concrete Implementation</label>
    <nameField>
        <displayFormat>CCI-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concrete Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Concrete_Implementation__c/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <label>Implementation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Concrete_Implementation__c/fields/Interface__c.field-meta.xml
<CustomField>
    <fullName>Interface__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Interface</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IoC_Object_Helper.cls
public with sharing class IoC_Object_Helper 
{
    // WHERE clause for Checkmarx
	public static List<Concrete_Implementation__c> getAllImplementations()
    {
        return [SELECT Interface__c, Implementation__c FROM Concrete_Implementation__c WHERE Id != NULL];
    }
    
    public static Concrete_Implementation__c getImplementation(string p_interface)
    {
        List<Concrete_Implementation__c> items = [SELECT Interface__c, Implementation__c FROM Concrete_Implementation__c WHERE Interface__c = :p_interface];
        
        if(items.isEmpty())
        {
            throw new IoC_NoImplementationException();
        }
        
        return items.get(0);
    }
    
    public static void createImplementation(string p_interface, string p_implementation)
    {
        Concrete_Implementation__c ci = new Concrete_Implementation__c
            (
                Interface__c = p_interface,
                Implementation__c = p_implementation
            );
        
        database.upsert(ci, Concrete_Implementation__c.Interface__c);
    }
}