force-app/main/default/objects/Concrete_Implementation__c/Concrete_Implementation__c.object-meta.xml
<CustomObject>
    <label>Concrete Implementation</label>
    <nameField>
        <displayFormat>CCI-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concrete Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Concrete_Implementation__c/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <label>Implementation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IoC_Object_Helper_Test.cls
@isTest
public class IoC_Object_Helper_Test 
{
	@isTest
    static void TestCreate()
    {
        IoC_Object_Helper.createImplementation('IFiles', 'Core_Files');
        
        integer count = [SELECT count() FROM Concrete_Implementation__c];
        
        system.assertEquals(1, count);
    }
    
    @isTest
    static void TestGetAll()
    {
        IoC_Object_Helper.createImplementation('IFiles', 'Core_Files');
        
        List<Concrete_Implementation__c> items = IoC_Object_Helper.getAllImplementations();
        
        system.assertEquals(1, items.size());
    }
    
    @isTest
    static void TestGetSingle()
    {
        IoC_Object_Helper.createImplementation('IFiles', 'Core_Files');
        
        Concrete_Implementation__c item = IoC_Object_Helper.getImplementation('IFiles');
        
        system.assertEquals('Core_Files', item.Implementation__c);
    }
    
    @isTest
    static void TestGetSingleException()
    {
        try
        {
	        Concrete_Implementation__c item = IoC_Object_Helper.getImplementation('IFiles');

			system.assert(false);
        }
		catch(IoC_NoImplementationException ex)
        {
            system.assert(true);
        }
    }
}